services:
  soil:
    build: "./images/smtp-garden-soil"
    image: smtp-garden-soil:latest
  aiosmtpd:
    build:
      context: "./images/aiosmtpd"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo"
    image: smtp-garden-aiosmtpd:latest
    ports:
    - 127.0.0.1:2504:25
  exim:
    build:
      context: "./images/exim"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo"
    image: smtp-garden-exim:latest
    ports:
      - 127.0.0.1:2503:25
  james:
    build:
      context: "./images/james"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo"
    image: smtp-garden-james:latest
    ports:
      - 127.0.0.1:2502:25
  postfix:
    build:
      context: "./images/postfix"
      args:
        APP_VERSION: "master"
        MYDESTINATION: "postfix"
        RELAYHOST: "echo"
    image: smtp-garden-postfix:latest
    ports:
      - 127.0.0.1:2501:25
  sendmail:
    build:
      context: "./images/sendmail"
      args:
        APP_VERSION: "8.18.1"
        RELAYHOST: "echo"
    image: smtp-garden-sendmail:latest
    ports:
    - 127.0.0.1:2505:25
  echo:
    build:
      context: "./images/echo"
    image: smtp-garden-echo:latest
    ports:
      - 127.0.0.1:25:25
  opensmtpd:
    build:
      context: "./images/opensmtpd"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo"
    image: smtp-garden-opensmtpd:latest
    ports:
      - 127.0.0.1:2506:25
  nullmailer:
    build:
      context: "./images/nullmailer"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo"
    image: smtp-garden-nullmailer:latest
    ports:
      - 127.0.0.1:2507:25
  msmtp:
    build:
      context: "./images/msmtp"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo"
    image: smtp-garden-msmtp:latest
    ports:
      - 127.0.0.1:2508:25
  dovecot:
    build:
      context: "./images/dovecot"
      args:
        APP_VERSION: "main"
        RELAYHOST: "echo"
    image: smtp-garden-dovecot:latest
    ports:
      - 127.0.0.1:2401:24
      - 127.0.0.1:2601:587
