services:
  aiosmtpd:
    build:
      context: "./images/aiosmtpd"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo"
    image: smtp-garden-aiosmtpd:latest
    ports:
    - 127.0.0.1:2504:25
  exim:
    build:
      context: "./images/exim"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo"
    image: smtp-garden-exim:latest
    ports:
      - 127.0.0.1:2503:25
  james:
    build:
      context: "./images/james"
      args:
        RELAYHOST: "echo"
    image: smtp-garden-james:3.8.1
    ports:
      - 127.0.0.1:2502:25
  postfix:
    build:
      context: "./images/postfix"
      args:
        APP_VERSION: "master"
        MYDESTINATION: "postfix"
        RELAYHOST: "echo"
    image: smtp-garden-postfix:latest
    ports:
      - 127.0.0.1:2501:25
  sendmail:
    build:
      context: "./images/sendmail"
      args:
        APP_VERSION: "8.18.1"
        RELAYHOST: "echo"
    image: smtp-garden-sendmail:latest
    ports:
    - 127.0.0.1:2505:25
  echo:
    build:
      context: "./images/echo"
    image: smtp-garden-echo:latest
    ports:
      - 127.0.0.1:25:25
  opensmtpd:
    build:
      context: "./images/opensmtpd"

