networks:
  smtp:
    
services:
  soil:
    build: "./images/smtp-garden-soil"
    image: smtp-garden-soil:latest

  dns-mx:
    build:
      context: "./images/dnsmasq"
      args:
        APP_VERSION: "master"
    image: smtp-garden-dnsmasq:latest
    hostname: dns-mx.smtp.garden
    volumes:
      - ./images/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      smtp:
        aliases:
          - dns-mx.smtp.garden

  echo:
    build:
      context: "./images/echo"
    image: smtp-garden-echo:latest
    hostname: echo.smtp.garden
    networks:
      smtp:
        aliases:
          - echo.smtp.garden
    ports:
      - 127.0.0.1:25:25

  aiosmtpd:
    build:
      context: "./images/aiosmtpd"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-aiosmtpd:latest
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    hostname: aiosmtpd.smtp.garden
    volumes:
      - ./images/aiosmtpd/home:/home
    networks:
      smtp:
        aliases:
          - aiosmtpd.smtp.garden
    ports:
    - 127.0.0.1:2501:25
  
  courier:
    build:
      context: "./images/courier"
      args:
        APP_VERSION: "1.3.13"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-courier:latest
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    hostname: courier.smtp.garden
    volumes:
      - ./images/courier/home:/home
    networks:
      smtp:
        aliases:
          - courier.smtp.garden
    ports:
      - 127.0.0.1:2502:25

  courier-msa:
    build:
      context: "./images/courier-msa"
      args:
        APP_VERSION: "1.3.13"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-courier-msa:latest
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    hostname: courier-msa.smtp.garden
    volumes:
      - ./images/courier-msa/home:/home
    networks:
      smtp:
        aliases:
          - courier-msa.smtp.garden
    ports:
      - 127.0.0.1:2601:587

  dovecot:
    build:
      context: "./images/dovecot"
      args:
        APP_VERSION: "main"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-dovecot:latest
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    hostname: dovecot.smtp.garden
    volumes:
      - ./images/dovecot/home:/home
    networks:
      smtp:
        aliases:
          - dovecot.smtp.garden
    ports:
      - 127.0.0.1:2401:24
      - 127.0.0.1:2602:587
  
  dovecot-msa:
    build:
      context: "./images/dovecot-msa"
      args:
        APP_VERSION: "main"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-dovecot-msa:latest
    hostname: dovecot-msa.smtp.garden
    networks:
      smtp:
        aliases:
          - dovecot-msa.smtp.garden
    ports:
      - 127.0.0.1:2603:587

  exim:
    build:
      context: "./images/exim"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-exim:latest
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    hostname: exim.smtp.garden
    volumes:
      - ./images/exim/smtp-garden-domains:/etc/smtp-garden-domains
      - ./images/exim/home:/home
    networks:
      smtp:
        aliases:
          - exim.smtp.garden
    ports:
      - 127.0.0.1:2503:25

  james:
    build:
      context: "./images/james"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-james:latest
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    hostname: james.smtp.garden
    volumes:
      - ./images/james/home:/home
      - ./images/james/inbox:/app/james/mail/inbox
    networks:
      smtp:
        aliases:
          - james.smtp.garden
    ports:
      - 127.0.0.1:2504:25

  james-maildir:
    build:
      context: "./images/james-maildir"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-james-maildir:latest
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    hostname: james.smtp.garden
    volumes:
      - ./images/james-maildir/home:/home
      - ./images/james-maildir/inbox:/app/james/mail/inbox
    networks:
      smtp:
        aliases:
          - james.smtp.garden
    ports:
      - 127.0.0.1:2504:25


  msmtp:
    build:
      context: "./images/msmtp"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-msmtp:latest
    hostname: msmtp.smtp.garden
    networks:
      smtp:
        aliases:
          - msmtp.smtp.garden
    ports:
      - 127.0.0.1:2505:25

  nullmailer:
    build:
      context: "./images/nullmailer"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-nullmailer:latest
    hostname: nullmailer.smtp.garden
    networks:
      smtp:
        aliases:
          - nullmailer.smtp.garden
    ports:
      - 127.0.0.1:2507:25

  opensmtpd:
    build:
      context: "./images/opensmtpd"
      args:
        APP_VERSION: "master"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-opensmtpd:latest
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    hostname: opensmtpd.smtp.garden
    volumes:
      - ./images/opensmtpd/home:/home
    networks:
      smtp:
        aliases:
          - opensmtpd.smtp.garden
    ports:
      - 127.0.0.1:2508:25

  postfix:
    build:
      context: "./images/postfix"
      args:
        APP_VERSION: "master"
        MYDESTINATION: "postfix"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-postfix:postcot
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    hostname: postfix.smtp.garden
    volumes:
      - ./images/postfix/home:/home
    networks:
      smtp:
        aliases:
          - postfix.smtp.garden
    ports:
      - 127.0.0.1:2509:25

  sendmail:
    build:
      context: "./images/sendmail"
      args:
        APP_VERSION: "8.18.1"
        RELAYHOST: "echo.smtp.garden"
    image: smtp-garden-sendmail:latest
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    hostname: sendmail.smtp.garden
    volumes:
      - ./images/sendmail/spool:/var/spool
    networks:
      smtp:
        aliases:
          - sendmail.smtp.garden
    ports:
      - 127.0.0.1:2510:25

