FROM smtp-garden-soil:latest

# Version B: default conf files, with minimal config changes
# (warning, this causes massive log spam. These config settings
# need additional editing)

ARG APP_VERSION
#ADD conf /app/conf

# Setup environment
RUN apt -y update && apt -y upgrade \
    && apt -y --no-install-recommends install unzip openjdk-21-jdk maven libdb-dev m4 libc6 libc6-dev \
    && cd /app \
    && git clone --recurse-submodules https://github.com/apache/james-project.git \
    && echo "Building..." \
    && cd /app/james-project \
    && git checkout "$APP_VERSION" \
# Build (warning, takes long time)
    && mvn -T $(nproc) -DskipTests clean install \
    && echo "Deploying jars..." \
    && mkdir /app/james \
    && cp -r /app/james-project/server/apps/jpa-app/target/james-server-jpa-app.* /app/james/
# (Break in RUN, for reconfiguration without rebuilding, at cost of image size)

# Configure
ARG RELAYHOST=echo
RUN find /app/james-project/server/apps/spring-app/src/main/resources -maxdepth 1 -type f -exec cp -t /app/james/conf {} + \
    && cp /app/conf/mailetcontainer.xml /app/james/conf \
    && cp /app/conf/smtpserver.xml /app/james/conf \
    && cp /app/conf/activemq.properties /app/james/conf \
    && cp /app/conf/keystore /app/james/keystore \
    && sed -i "s/<gateway>__RELAYHOST__/<gateway>${RELAYHOST}/" /app/james/conf/mailetcontainer.xml \
# (Cleanup, saves a little bit of space)
    && rm -r /app/james-project \
    && apt -y purge openjdk-21-jdk && apt -y autoremove && apt -y install openjdk-21-jre \
    && rm -r /root/.m2

# Go
CMD ["java", \
     "-javaagent:/app/james/james-server-jpa-app.lib/openjpa-4.0.0.jar", \
     "-Dlogback.configurationFile=/app/james/conf/logback.xml", \
     "-Dworking.directory=/app/james", \
     "-jar", "/app/james/james-server-jpa-app.jar"]
